version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data:/var/lib/rabbitmq
      - ./rabbitmq-defs.json:/opt/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf